ktor:
    application:
        modules:
            - com.lifted.ApplicationKt.module
    deployment:
        port: 8080
    development: true  # Set to false in production
    admin:
        username: "admin" # only used for 'development: true'
        password: "admin"

app:
    version: ${appVersion}