ktor:
    application:
        modules:
            - com.lifted.ApplicationKt.module
    deployment:
        port: 8080
    development: true  # Set to false in production

app:
    version: ${appVersion}